Medicine/Medicine/Controllers/DoctorController.cs
using Medicine.Models;
using Medicine.Models.BusinessLogic;
using Medicine.Models.Doctors;
using Medicine.Models.Schedules;
using PagedList;
using System;
using System.Activities.Statements;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Data.Common;
using System.Data.Entity;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Medicine.Controllers
{
    public class DoctorController : Controller
    {
        private readonly ApplicationDbContext db = new ApplicationDbContext();
        private readonly DoctorBL doctorBl = new DoctorBL();

        #region Doctor 
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult DoctorList(int? page)
        {
            int pageSize = 10;
            int pageNumber = page ?? 1;
            List<Doctor> list = doctorBl.ListDoctors();
            return View(list.ToPagedList(pageNumber,pageSize));
        }
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult CreateDoctor(string email)
        {
            SelectList list = new SelectList(
                 new List<SelectListItem>
                 {
                    new SelectListItem {Value="1", Text = "Male" },
                    new SelectListItem {Value="2", Text ="Female" }
                 }, "Value", "Text");
            ViewBag.Sex = list;
            ViewBag.Type = new SelectValue().GetDoctorType();
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult CreateDoctor(Doctor doctor)
        {
            string userName = User.Identity.Name;
            if (ModelState.IsValid)
            {
                try
                {
                    doctorBl.AddDoctor(doctor, userName);
                    db.SaveChanges();
                    foreach (string fileName in Request.Files)
                    {
                        HttpPostedFileBase file = Request.Files[fileName];
                        if (file != null)
                        {
                            var name = DateTime.Now.ToFileTime() + Path.GetFileName(file.FileName);
                            if (file.ContentLength > 0)
                            {
                                // лучше оставить слеши Content/
                                if (!Directory.Exists(Server.MapPath("~/Content/Images/DifferentPictures/")))
                                {   // лучше оставить слеши Content/
                                    Directory.CreateDirectory(Server.MapPath("~/Content/Images/DifferentPictures/"));
                                }
                                // после Content можно не ставить / слэш
                                string path = Path.Combine(Server.MapPath("~/Content/Images/DifferentPictures") + "/" + name);
                                file.SaveAs(path);
                                // извлекаеться картинка +Content/ - слэш как разделитель
                                doctor.Photo = "/Content/Images/DifferentPictures/" + name;
                                db.Entry(doctor).State = EntityState.Modified;
                                db.SaveChanges();
                            }
                        }
                    }
                }
                catch (Exception)
                {
                    return View(doctor);
                }
            }
            return RedirectToAction("DoctorList");
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult EditDoctor(int id)
        {
            SelectList list = new SelectList(
                 new List<SelectListItem>
                 {
                    new SelectListItem {Value="1", Text = "Male" },
                    new SelectListItem {Value="2", Text ="Female" }
                 }, "Value", "Text");
            ViewBag.Sex = list;
            Doctor doctor = doctorBl.GetDoctor(id);
            ViewBag.Type = new SelectValue().GetDoctorType();
            TempData["UrlPictue"] = doctor.Photo;
            return View(doctor);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult EditDoctor(Doctor doctor)
        {   string userName = User.Identity.Name;
            string url = (string)TempData["UrlPictue"];
            foreach (string fileName in Request.Files)
            {
                HttpPostedFileBase file = Request.Files[fileName];
                if (file != null)
                {
                    var name = DateTime.Now.ToFileTime() + Path.GetFileName(file.FileName);
                    if (file.ContentLength > 0)
                    {
                        // лучше оставить слеши Content/
                        if (!Directory.Exists(Server.MapPath("~/Content/Images/DifferentPictures/")))
                        {   // лучше оставить слеши Content/
                            Directory.CreateDirectory(Server.MapPath("~/Content/Images/DifferentPictures/"));
                        }
                        // после Content можно не ставить / слэш
                        string path = Path.Combine(Server.MapPath("~/Content/Images/DifferentPictures") + "/" + name);
                        file.SaveAs(path);

                        if (url != doctor.Photo)
                        {
                            if (doctor.Sex == "1")
                            {
                                doctor.Sex = "Male";
                            }
                            else
                            {
                                doctor.Sex = "Female";
                            }
                            doctor.WhoModified = userName;
                            doctor.WhenModified = DateTime.Now;
                            doctor.Photo = "/Content/Images/DifferentPictures/" + name;
                            ViewBag.Type = new SelectValue().GetDoctorType();
                            db.Entry(doctor).State = EntityState.Modified;
                            db.SaveChanges();
                        }
                        else
                        {
                            if (doctor.Sex == "1")
                            {
                                doctor.Sex = "Male";
                            }
                            else
                            {
                                doctor.Sex = "Female";
                            }
                            doctor.WhoModified = userName;
                            doctor.WhenModified = DateTime.Now;
                            doctor.Photo = url;
                            db.Entry(doctor).State = EntityState.Modified;
                            db.SaveChanges();
                        }
                        return RedirectToAction("DoctorList");
                    }
                }
                if (doctor.Sex == "1")
                {
                    doctor.Sex = "Male";
                }
                else
                {
                    doctor.Sex = "Female";
                }
                doctor.WhoModified = userName;
                doctor.WhenModified = DateTime.Now;
                doctor.Photo = url;
                ViewBag.Type = new SelectValue().GetDoctorType();
                db.Entry(doctor).State = EntityState.Modified;
                db.SaveChanges();
            }

            return RedirectToAction("DoctorList");
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteDoctor(int id)
        {
            string userName = User.Identity.Name;
            doctorBl.DeleteDoctor(id, userName);
            TempData["RedirectPartial"] = true;
            return RedirectToAction("DoctorList");
        }


        [HttpGet]
        [Authorize(Roles = "Doctor,Admin")]
        public ActionResult EditDoctorByName(string user)
        {
            SelectList list = new SelectList(
                 new List<SelectListItem>
                 {
                    new SelectListItem {Value="1", Text = "Male" },
                    new SelectListItem {Value="2", Text ="Female" }
                 }, "Value", "Text");
            ViewBag.Sex = list;
            Doctor doctor = doctorBl.GetDoctorByName(user);
            ViewBag.Type = new SelectValue().GetDoctorType();
            TempData["UrlPictue"] = doctor.Photo;
            return View(doctor);
        }

        [HttpPost]
        [Authorize(Roles = "Doctor,Admin")]
        public ActionResult EditDoctorByName(Doctor doctor)
        {
            string userName = User.Identity.Name;
            string url = (string)TempData["UrlPictue"];
            foreach (string fileName in Request.Files)
            {
                HttpPostedFileBase file = Request.Files[fileName];
                if (file != null)
                {
                    var name = DateTime.Now.ToFileTime() + Path.GetFileName(file.FileName);
                    if (file.ContentLength > 0)
                    {
                        // лучше оставить слеши Content/
                        if (!Directory.Exists(Server.MapPath("~/Content/Images/DifferentPictures/")))
                        {   // лучше оставить слеши Content/
                            Directory.CreateDirectory(Server.MapPath("~/Content/Images/DifferentPictures/"));
                        }
                        // после Content можно не ставить / слэш
                        string path = Path.Combine(Server.MapPath("~/Content/Images/DifferentPictures") + "/" + name);
                        file.SaveAs(path);

                        if (url != doctor.Photo)
                        {
                            if (doctor.Sex == "1")
                            {
                                doctor.Sex = "Male";
                            }
                            else
                            {

Medicine/Medicine/Controllers/ScheduleController.cs
using Medicine.Models;
using Medicine.Models.BusinessLogic;
using Medicine.Models.Doctors;
using Medicine.Models.Pacients;
using Medicine.Models.Schedules;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Medicine.Controllers
{
    public class ScheduleController : Controller
    {
        private readonly ApplicationDbContext db = new ApplicationDbContext();
        private readonly ScheduleBL scheduleBL = new ScheduleBL();

        #region Schedule

        #endregion

        #region Timetable

        public ActionResult TimetableList(int?page)
        {
            int pageSize = 5;
            int pageNumber = page ?? 1;
            ViewBag.MeetingList = scheduleBL.ListMeetTime();
            List<Timetable> list = scheduleBL.ListTimetable();
            return View(list.ToPagedList(pageNumber,pageSize));
        }

        public ActionResult CreateTimetable()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateTimetable(Timetable table)
        {
            if (ModelState.IsValid)
            {
                string userName = User.Identity.Name;
                scheduleBL.AddTimetable(table, userName);
                return RedirectToAction("TimetableList");
            }
            return View(table);
        }
        public ActionResult EditTimetable(int id)
        {
            Timetable time = scheduleBL.GetTimetable(id);
            return View(time);
        }
        [HttpPost]
        public ActionResult EditTimetable(Timetable time)
        {
            if (ModelState.IsValid)
            {
                string userName = User.Identity.Name;
                scheduleBL.ChangeTimetable(time, userName);
                return RedirectToAction("TimetableList");
            }
            return View(time);
        }
        public ActionResult DeleteTimetable(int id)
        {
            string userName = User.Identity.Name;
            scheduleBL.DeleteTimetable(id, userName);
            TempData["RedirectPartial"] = true;
            return RedirectToAction("TimetableList");
        }
        #endregion

        #region MeetTime

        public ActionResult CreateMeetTime(int id)
        {
            ViewBag.Id = id;
            return View();
        }
        [HttpPost]
        public ActionResult CreateMeetTime(MeetTime time, int id)
        {
            ViewBag.Id = id;

            if (ModelState.IsValid)
            {
                string userName = User.Identity.Name;
                scheduleBL.AddMeetTime(time, userName, id);
                return RedirectToAction("TimetableList");
            }
            return View(time);
        }
        public ActionResult EditMeetTime(int id)
        {
            MeetTime time = scheduleBL.GetMeetTime(id);
            return View(time);
        }
        [HttpPost]
        public ActionResult EditMeetTime(MeetTime time)
        {
            if (ModelState.IsValid)
            {
                string userName = User.Identity.Name;
                scheduleBL.ChangeMeetTime(time, userName);
                return RedirectToAction("TimetableList");
            }
            return View(time);
        }
        public ActionResult DeleteMeetTime(int id)
        {
            string userName = User.Identity.Name;
            scheduleBL.DeleteMeeTime(id, userName);
            TempData["RedirectPartial"] = true;
            return RedirectToAction("TimetableList");
        }

        public ActionResult ScheduleList(int? page)
        {
            int pageSize = 10;
            int pageNumber = page ?? 1;
            List<Doctor> list = new DoctorBL().ListDoctors();
            return View(list.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult WorkingJournal(int id, int?page)
        {
            int pageSize = 20;
            int pageNumber = page ?? 1 ;
            ViewBag.DoctorId = id;
            List<Schedule> schedule = scheduleBL.WorkingJournalList(id);
            return View(schedule.ToPagedList(pageNumber,pageSize));
        }

        public ActionResult CreateJournal(int id)
        {
            ViewBag.DoctorId = id;
            ViewBag.Timetable = new SelectValue().GetTimetable();
            return PartialView();
        }
        [HttpPost]

        public ActionResult CreateJournal(Schedule schedule, int id)
        {
            ViewBag.DoctorId = id;
            if (ModelState.IsValid)
            {
                string userName = User.Identity.Name;
                scheduleBL.AddWorkingJournal(schedule, userName, id);
                return RedirectToAction("WorkingJournal", new { id = id });
            }
            ViewBag.Timetable = new SelectValue().GetTimetable();
            return PartialView(schedule);
        }
        #endregion

        #region RegistrationToAppointmant
        public ActionResult AppointmentForm()
        {
            return View();
        }
        public ActionResult RegisterForm(DateTime? appointmantDate, string doctorName)
        {
            List<Schedule> list = (from d in db.Schedule
                                   where (d.Doctor.Name + d.Doctor.Sername).Contains(doctorName) && d.Date == appointmantDate
                                   select d).ToList();
            return PartialView(list);

        }
        public ActionResult RegisterToAnAppointmant(int id)
        {
            Schedule schedule = db.Schedule.Where(x => x.ScheduleId == id).FirstOrDefault();
            return View(schedule);
        }
        [HttpPost]
        public ActionResult RegisterToAnAppointmant(Schedule schedule)
        {
            if (ModelState.IsValid)
            {
                string userName = User.Identity.Name;
                Pacient currentUser = db.Pacients.Where(x => x.UserName == userName).FirstOrDefault();
                int Id = currentUser.PacientId;
                scheduleBL.RegisterAppointment(schedule, Id);
                return RedirectToAction("AppointmentForm");
            }
            return View(schedule);
        }
        #endregion

        #region AppointmantRegistration
        public ActionResult AppointmantRegistration(int id)
        {
            Schedule app = db.Schedule.Where(x => x.IsVisible && x.ScheduleId == id).FirstOrDefault();
            return View(app);
        }
        [HttpPost]
        public ActionResult AppointmantRegistration(Schedule schedule)
        {
            string userName = User.Identity.Name;
            Pacient pacient = db.Pacients.Where(x => x.UserName == userName).FirstOrDefault();
            if (ModelState.IsValid)
            {
                schedule.isBooked = true;
                schedule.PacientId = pacient.PacientId;
                db.Entry(schedule).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
           
            return View(schedule);
        }
        #endregion

        #region AppontmantsTime

        public ActionResult AppointmantsTime(DateTime date, int id )
        {
            List<Schedule> list = db.Schedule.Where(x => x.Date == date && x.DoctorId == id).ToList();
            ViewBag.Date = date;
            return View(list);
        }
        #endregion

    }
}

Medicine/Medicine/Views/Home/AdminPanel.cshtml
@{
    ViewBag.Title = "Admin Panel";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="container">
    <div class="row">

        <div class="col s12 l2 m3">
            <a href="@Url.Action("TypeList","Doctor")">
                <div class="card z-depth-1 cardWrap">
                    <div class="card-content cardText">
                        <div style="text-align:center">
                            <div class="cardIcon">
                                <i class="material-icons">format_list_numbered</i>
                            </div>
                            <div>Doctor types</div>
                        </div>
                    </div>
                </div>
            </a>
        </div>

        <div class="col s12 l2 m3">
            <a href="@Url.Action("DoctorList","Doctor")">
                <div class="card z-depth-1 cardWrap">
                    <div class="card-content cardText">
                        <div style="text-align:center">
                            <div class="cardIcon">
                                <i class="material-icons">person</i>
                            </div>
                            <div>Doctors</div>
                        </div>
                    </div>
                </div>
            </a>
        </div>

        <div class="col s12 l2 m3">
            <a href="@Url.Action("ScheduleList","Schedule")">
                <div class="card z-depth-1 cardWrap">
                    <div class="card-content cardText">
                        <div style="text-align:center">
                            <div class="cardIcon">
                                <i class="material-icons">insert_drive_file</i>
                            </div>
                            <div>Schedule</div>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col s12 l2 m3">
            <a href="@Url.Action("PacientList","Pacient")">
                <div class="card z-depth-1 cardWrap">
                    <div class="card-content cardText">
                        <div style="text-align:center">
                            <div class="cardIcon">
                                <i class="material-icons">group</i>
                            </div>
                            <div>Patients</div>
                        </div>
                    </div>
                </div>
            </a>
        </div>

        <div class="col s12 l2 m3">
            <a href="@Url.Action("TimetableList","Schedule")">
                <div class="card z-depth-1 cardWrap">
                    <div class="card-content cardText">
                        <div style="text-align:center">
                            <div class="cardIcon">
                                <i class="material-icons">today</i>
                            </div>
                            <div>Timetable</div>
                        </div>
                    </div>
                </div>
            </a>
        </div>

    </div>
</div>

Medicine/Medicine/Views/Home/DoctorsView.cshtml
@model PagedList.IPagedList<Medicine.Models.Doctors.Doctor>
@using PagedList.Mvc;
@{
    ViewBag.Title = "DoctorsView";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div class="container">
    <div class="row">
        <div>
            @Html.Action("_DoctorViewPartial", "Home")
        </div>

        <div id="result">
            @foreach (var item in Model)
            {
                string name = item.Name + " " + item.Sername;
                <div class="col l3 m4 s12 card z-depth-1-half doctor-wrapper">
                    <div class="img-wraper">
                        <div style="height:200px!important;">
                            <img src="@item.Photo" class="doc-img"/>
                        </div>
                       
                    </div>
                    <a class="inf-block" href="@Url.Action("ShortDoctorInfo","Doctor", new { id = item.DoctorId})"  >
                        <div class="text-name center" data-id="@item.DoctorId">
                            <span>@name</span>
                            <br />
                            <span>@item.DoctorType.Name</span>
                        </div>
                    </a>
                    <div class="center">
                        <a class="btn schedule-btn " href="@Url.Action("ScheduleByDoctor", "Home",new { id = item.DoctorId})">Schedule</a>
                    </div>
                </div>
            }
        </div>
    </div>
</div>
@if (Model.Count > 12)
{
    <div class="center">
        @Html.PagedListPager(Model, page => Url.Action("DoctorsView", new { page }))
    </div>
}
<div style="height:150px;"></div>

Medicine/Medicine/Views/Home/EditPassword.cshtml
@model Medicine.Models.ChangePasswordViewModel
@{
    ViewBag.Title = "Change Password";
}
<div class="container">
    <div class="row">
        <section id="loginForm">
            @using (Html.BeginForm("EditPassword", "Home", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.ValidationSummary()
                @Html.AntiForgeryToken()
                <div class="col l4 push-l4 m4 push-m4 s12 card z-depth-1-half form-wraper">
                    <div class="red-circle">
                        <i class="material-icons medium center">near_me</i>
                    </div>
                    <div class="col l10 push-l1 m10 push-m1 s10 push-s1 input-style">
                        <input type="password" placeholder="Old Password" name="OldPassword" />
                    </div>

                    <div class="col l10 push-l1 m10 push-m1 s10 push-s1 input-style">
                        <input type="password" placeholder="New Password" name="NewPassword" />
                    </div>
                    <div class="col l10 push-l1 m10 push-m1 s10 push-s1 input-style">
                        <input type="password" placeholder="Repeat Password" name="ConfirmPassword" />
                    </div>
                    <div class="col l10 push-l1 m10 push-m1 s10 push-s1">
                        <input class="btn log-in-btn" type="submit" value="Change password" />
                    </div>
                </div>
            }
        </section>

    </div>
</div>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Medicine/Medicine/Views/Home/ScheduleByDoctor.cshtml
@model List<Medicine.Models.Schedules.Schedule>
@{
    ViewBag.Title = "ScheduleByDoctor";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
    int? number = ViewBag.Number;
    int id = ViewBag.DoctorId;
    DateTime nDate = new DateTime();
}
<script src="~/Scripts/jquery-3.1.1.min.js" type="text/javascript"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js" type="text/javascript"></script>
<link href="~/Scripts/air-datepicker-master/dist/css/datepicker.min.css" rel="stylesheet" />
<script src="~/Scripts/air-datepicker-master/dist/js/datepicker.min.js"></script>

<div class="container">
    <div class="row row-card-wrap">
        <div class="col l12 m12 s12 time-block-wrapper" id="selected">
            <div class="col l12 m12 s12 card color-line z-depth-1-half">
                @if (ViewBag.Date.Count != 0)
            {
                DateTime newDate = ViewBag.Time;
                    <a href="@Url.Action("ScheduleByDoctor", "Home", new { id = id, newDate = newDate, number = number})" class="btn week-button"><i class="material-icons right">send</i>Next week</a>
                }
            </div>
            @if (Model.Count > 0 && ViewBag.Date.Count != 0)
            {
                foreach (var d in ViewBag.Date)
                {
                    DateTime nd = d.Date;
                    string date = nd.Day.ToString();
                    string dayOfWeek = nd.DayOfWeek.ToString();
                    string month = System.Globalization.CultureInfo.InvariantCulture.DateTimeFormat.GetMonthName(nd.Month);
                    <div class="time-block">
                        <a href="@Url.Action("AppointmantsTime","Schedule", new { date = nd, id = id})">
                            <div class="top-title">
                                <div class="col l12 m12 s12">
                                    <p>@date @month</p>
                                </div>
                                <p>@dayOfWeek</p>
                            </div>
                        </a>
                    </div>
                }
            }
            else
            {
                <h5 class="center-align" style="display:block;margin-top:100px;">Looks like, doctor doesn't have available appointments.</h5>
            }
        </div>
    </div>
</div>
<div style="height:300px;">

</div>

Medicine/Medicine/Views/Home/_SelectedDoctorPartial.cshtml
@model List<Medicine.Models.Doctors.Doctor>

<div style="min-height:300px;">

    @if (Model.Count > 0)
    {
        <div>
            @foreach (var item in Model)
            {
                string name = item.Name + " " + item.Sername;

                <div class="col l3 m4 s12 card z-depth-1-half doctor-wrapper">
                    <div class="img-wraper">
                        <img src="@item.Photo" class="doc-img" />
                    </div>
                    <a class="inf-block" href="@Url.Action("ShortDoctorInfo","Doctor", new { id = item.DoctorId})">
                        <div class="text-name center">
                            <span>@name</span>
                            <br />
                            <span>@item.DoctorType.Name</span>
                        </div>
                    </a>
                    <div class="center">
                        <a class="btn schedule-btn " href="@Url.Action("ScheduleByDoctor", "Home",new { id = item.DoctorId})">Schedule</a>
                    </div>
                </div>
            }
        </div>

    }
    else
    {
        <h5 class="center">Doctor doesn't exist by your parameters.<br /><br /> Try another parameters</h5>


    }
</div>

Medicine/Medicine/Views/Home/_WorkingDayPartial.cshtml
@model List<Medicine.Models.Schedules.Schedule>
@{
    ViewBag.Title = "_WorkingDayPartial";
    Layout = "~/Views/Shared/_EmptyLayout.cshtml";

}

<div class="col l12 m12 s12 time-block-wrapper" id="selected">
    <div class="col l12 m12 s12 color-line">
        <a href="" class="btn week-button"><i class="material-icons left">reply</i>go back</a>
    </div>

    <div style="margin-top:65px;">
        @if (Model.Count > 0)
        {

            <div class="top-title single-time-block">
                @{
                    DateTime nd = ViewBag.Date;
                    string date = nd.Day.ToString();
                    string dayOfWeek = nd.DayOfWeek.ToString();
                    string month = System.Globalization.CultureInfo.InvariantCulture.DateTimeFormat.GetMonthName(nd.Month);
                }
                <div class="col l12 m12 s12">
                    <p>@date @month</p>
                </div>
                <p>@dayOfWeek</p>
            </div>

                    foreach (var item in Model)
                    {
                        <div class="single-time-block">
                            @if (item.TimeFrom.Value.ToShortDateString() == item.Date.ToShortDateString())
                            {
                                if (item.isBooked == true)
                                {
                                    <div class="time-text-block-booked">
                                        <p>@item.TimeFrom.Value.ToShortTimeString()  - @item.TimeTo.Value.ToShortTimeString()</p>
                                    </div>
                                }
                                else
                                {
                                    <div class="time-text-block">
                                        <a href="@Url.Action("AppointmantRegistration","Schedule",new { id = item.ScheduleId})">
                                            <p>@item.TimeFrom.Value.ToShortTimeString()  - @item.TimeTo.Value.ToShortTimeString()</p>
                                        </a>
                                    </div>
                                }

                            }
                        </div>
                        }

                    }
                    else
                    {
                        <p>No data</p>
                    }

    </div>
 


</div>

<script src="~/Scripts/jquery-3.1.1.min.js" type="text/javascript"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js" type="text/javascript"></script>