BookStore/WebUI/Models/BooksListViewModel.cs
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebUI.Models
{
    public class BooksListViewModel
    {
        public IEnumerable<Book> Books { get; set; }
        public PaginInfo PagingInfo { get; set; }
        public string CurrentGenre { get; set; }
    }
}

BookStore/WebUI/Models/CartIndexViewModel.cs
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebUI.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

BookStore/WebUI/Models/PaginInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebUI.Models
{
    public class PaginInfo
    {
        public int TotalItems { get; set; }     // Total amount of books
        public int ItemsPerPage { get; set; }   // Books amount per page
        public int CurrentPage { get; set; }    // Number of current page
        public int TotalPages                   // Total pages amount
        {
            get { return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage); }
        }
    }
}

BookStore/WebUI/Controllers/AdminController.cs
using Domain.Abstract;
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class AdminController : Controller
    {
        private IBookRepository repository;
        public AdminController(IBookRepository repo)
        {
            repository = repo;
        }
        public ViewResult Index()
        {
            return View(repository.Books);
        }
        public ViewResult Edit(int bookId)
        {
            Book book = repository.Books.FirstOrDefault(b => b.BookId == bookId);
            return View(book);
        }
        [HttpPost]
        public ActionResult Edit(Book book)
        {
            if (ModelState.IsValid)
            {
                repository.SaveBook(book);
                TempData["message"] = string.Format("Book's chnages \"{0} saved", book.Name);
                return RedirectToAction("Index");
            }
            else
            {
                return View(book);
            }
            
        }
    }
}

BookStore/WebUI/Controllers/BooksController.cs
using Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class BooksController : Controller
    {
        private IBookRepository repository;

        // number of books on the page
        public int pageSize = 2;

       public BooksController(IBookRepository repo)
        {
            repository = repo;
        }

        public ViewResult List(string genre, int page = 1)
        {
            BooksListViewModel model = new BooksListViewModel
            {
                Books = repository.Books.Where(b => genre == null || b.Genre == genre).OrderBy(book => book.BookId).Skip((page - 1) * pageSize).Take(pageSize),
                PagingInfo = new PaginInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = genre==null ? repository.Books.Count(): 
                        repository.Books.Where(x=>x.Genre == genre).Count()
                },
                CurrentGenre = genre
            };    
            return View(model);
        }
    }
}

BookStore/WebUI/Controllers/CartController.cs
using Domain.Abstract;
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class CartController : Controller
    {
        private IBookRepository repository;
        private IOrderProcessor orderProcessor;

        public ViewResult Index(Cart cart,string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl  
            });
        }

        public CartController(IBookRepository repo, IOrderProcessor processor)
        {
            repository = repo;
            orderProcessor = processor;
        }
   
        public RedirectToRouteResult AddToCart(Cart cart,int bookId, string returnUrl)
        {
            Book book = repository.Books.FirstOrDefault(x => x.BookId == bookId);
            if (book != null)
            {
                // 1 - it's books number, becasue wwe don't have filed for input books quantity 
                cart.AddItem(book, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart,int bookId, string returnUrl)
        {
            Book book = repository.Books.FirstOrDefault(x => x.BookId == bookId);
            if (book != null)
            {
                // 1 - it's books number, becasue wwe don't have filed for input books quantity 
                cart.RemoveLine(book);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }
        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }
        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your basket is empty!");
            }
            if (ModelState.IsValid)
            {
                orderProcessor.ProcessorOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(new ShippingDetails());
            }
           
        }
    }
}

BookStore/WebUI/Controllers/NavController.cs
using Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class NavController : Controller
    {
        private IBookRepository repository;

        public NavController(IBookRepository repo)
        {
            repository = repo;
        }

       public PartialViewResult Menu(string genre=null)
        {
            ViewBag.SelectedGenre = genre;

            IEnumerable<string> genres = repository.Books
                .Select(book => book.Genre)
                .Distinct()
                .OrderBy(x => x);
            return PartialView(genres);
        }
    }
}

BookStore/WebUI/Views/Admin/Edit.cshtml
@model Domain.Entities.Book

@{
    ViewBag.Title = "Edit book";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="container">
    <div class="row">
        <div class="card-title">
            <h4>Edit book</h4>
        </div>
        <div class="">
            @using (Html.BeginForm())
            {
                @Html.EditorForModel()   
                <div>
                    <input type="submit" value="Save" class="btn yellow" />
                    @Html.ActionLink("Cancel", "Index", null, null, new { @class = "btn red" })
                </div>
            }
        </div>
    </div>
</div>

BookStore/WebUI/Views/Admin/Index.cshtml
@model IEnumerable<Domain.Entities.Book>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="container">
    <div class="row">
        <div>
            <h5>Books list</h5>
        </div>
        <table class="table striped">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.BookId)
                </th>
                <th >
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Author)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Genre)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th>Actions</th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.BookId
                    </td>
                    <td>
                       @Html.ActionLink(item.Name,"Edit",new { item.BookId})
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Author)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Genre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                       @using (Html.BeginForm("Delete","Admin"))
                       {
                           @Html.Hidden("BookId", item.BookId)
                           <input type="submit" class="btn" value="Delete" />
                       }
                    </td>
                </tr>
            }

        </table>

        <div>
            @Html.ActionLink("Add New", "Create",null, new { @class = "btn" })
        </div>
    </div>
 
</div>

BookStore/WebUI/Views/Books/List.cshtml
@using WebUI.Models

@model BooksListViewModel

@{
    ViewBag.Title = "List";
}

@foreach(var book in Model.Books)
{
    
    @Html.Partial("_BookSummary",book)
}
<div>
    @Html.PageLinks(Model.PagingInfo,x=>Url.Action("List",new { page = x, genre = Model.CurrentGenre}))
    
</div>

BookStore/WebUI/Views/Cart/Checkout.cshtml
@model Domain.Entities.ShippingDetails

@{
    ViewBag.Title = "BookStore: order form";
}

<h2>Make an order</h2>
<p>Please, enter your data</p>
@using (Html.BeginForm())
{
    @Html.ValidationSummary()
    <h5>Information</h5>
    <div class="input-field">
        <label>Your name:</label>
        @Html.TextBoxFor(x => x.Name)
    </div>
    foreach (var property in ViewData.ModelMetadata.Properties)
    {
        if (property.PropertyName!= "Name")
        {
            <div class="input-field">
                <label>
                    @(property.DisplayName ?? property.PropertyName)
                </label>
             @Html.TextBox(property.PropertyName,null)
                
            </div>
        }
    }

    <input type="submit" class="btn blue-grey" value="From order"/>
}

BookStore/WebUI/Views/Cart/Completed.cshtml
@{
    ViewBag.Title = "Order is completed";
}

<h2>Thank you.</h2>
<p>Your order will be sent in nearest time</p>

BookStore/WebUI/Views/Cart/Index.cshtml
@model WebUI.Models.CartIndexViewModel

@{
    ViewBag.Title = "BookStore: Your cart";
}

<h4>Index</h4>

<table>
    <thead>
        <tr>
            <th>Amount</th>
            <th>Name</th>
            <th>Price</th>
            <th>Sum</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
            <tr>
                <td>@line.Quantity</td>
                <td>@line.Book.Name @line.Book.Author</td>
                <td>@line.Book.Price.ToString("# $")</td>
                <td>@((line.Quantity*line.Book.Price).ToString("# $"))</td>
                <td>
                    @using (Html.BeginForm("RemoveFromCart", "Cart"))
                    {
                        @Html.Hidden("BookId", line.Book.BookId)
                        @Html.HiddenFor(x=>x.ReturnUrl)
                        <input type="submit" class="btn red" value="Delete book" />
                    }
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td>Total cost</td>
            <td>@Model.Cart.ComputeTotalValue().ToString("# $")</td>
        </tr>
    </tfoot>
</table>
<div>
    <a href="@Model.ReturnUrl" class="btn yellow">Continue shopping</a>
    @Html.ActionLink("Form the order","Checkout","Cart",null, new { @class = "btn blue"})
</div>

BookStore/WebUI/Views/Cart/Summary.cshtml
@model Domain.Entities.Cart

<div>
    @Html.ActionLink("Make order", "Index", "Cart",
    new { returnUrl = Request.Url.PathAndQuery },
    new { @class = "btn" })
</div>

<div>
    <b>Your basket</b>
    @Model.Lines.Sum(x=>x.Quantity) books,
    @Model.ComputeTotalValue().ToString("# $")
</div>

BookStore/WebUI/Views/Shared/_AdminLayout.cshtml
@{ 
    Layout = null;
}
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
<link href="~/Content/materialize/css/materialize.min.css" rel="stylesheet" media="screen,projection" />
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="center" style="background-color:#29a599; height:30px; color: white;padding-top:5px;">
                @if (TempData["message"] != null)
                {
                    <div>@TempData["message"]</div>
                }
            </div>
                @RenderBody()
          
        </div>
    </div>
  
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/materialize/materialize.min.js"></script>
</body>
</html>

BookStore/WebUI/Views/Shared/_BookSummary.cshtml
@model Domain.Entities.Book

<div class="card">
    <div>
        <h4>@Model.Name - @Model.Author </h4>
        <p>@Model.Description</p>
    </div>
    <div class="">
        <h5>@Model.Price.ToString("# $")</h5>
    </div>
    <div>
        @using (Html.BeginForm("AddToCart", "Cart"))
        {
            @Html.HiddenFor(x=>x.BookId)
            @Html.Hidden("returnUrl",Request.Url.PathAndQuery)
            <input type="submit" class="btn" value="Add to cart"/>
        }
    </div>
</div>
<hr />

BookStore/WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/materialize/css/materialize.min.css" rel="stylesheet" media="screen,projection"/>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div style="float:left; height:60px;">
        <a href="#">Book store</a>
        @Html.Action("Summary","Cart")
    </div>
    <div class="row">
        <div class="col l2 m4 s12">
            <menu>
              @Html.Action("Menu","Nav")
            </menu>
        </div>

        <main class="col l8 m8 s12">

            @RenderBody()

        </main>
    </div>
    <footer>

    </footer>

    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/materialize/materialize.min.js"></script>
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</body>
</html>